export default {
  name: 'contactFormSettings',
  title: 'Форма обратной связи — тексты',
  type: 'document',
  fields: [
    { name: 'nameLabel', title: 'Поле «Имя»', type: 'localeString' },
    { name: 'companyLabel', title: 'Поле «Компания»', type: 'localeString' },
    { name: 'phoneLabel', title: 'Поле «Телефон»', type: 'localeString' },
    { name: 'emailLabel', title: 'Поле «Email»', type: 'localeString' },
    { name: 'messageLabel', title: 'Поле «Сообщение»', type: 'localeString' },
    { name: 'messagePlaceholder', title: 'Плейсхолдер поля сообщения', type: 'localeString' },
    { name: 'fileLabel', title: 'Подпись «Прикрепить файл»', type: 'localeString' },
    { name: 'chooseFileLabel', title: 'Кнопка «Выбрать файл»', type: 'localeString' },
    { name: 'noFileLabel', title: 'Текст «Файл не выбран»', type: 'localeString' },
    { name: 'submitLabel', title: 'Кнопка отправки', type: 'localeString' },
    { name: 'sendingLabel', title: 'Текст во время отправки', type: 'localeString' },
    { name: 'successMessage', title: 'Сообщение об успехе', type: 'localeText' },
    { name: 'errorMessage', title: 'Сообщение об ошибке', type: 'localeText' },
    { name: 'requiredMessage', title: 'Сообщение о незаполненных полях', type: 'localeText' },
  ],
  preview: { prepare: () => ({ title: 'Форма обратной связи — тексты' }) },
};
